### ISSUE TITLE
Doubt / Suggestion about type casting

### ISSUE THREAD

**Issue by e-ruiz** [php-fig-rectified/fig-rectified-standards#13]
Hi Guys.

I am little confuse about type casting code style at [PSR-2-R](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md).

There is not any suggestion about the use (or not use) an space before the var, right?

So what would be better?
I can see only two valid possibilities.

```php
$var = (int) $value;
$var = (int)$value;
```

I prefer the first IMHO.
I know, is a very little detail, but why not?

Best regards.

**Comment by dereuromark** [comment]
PSR2R already uses and fixes to the latter. 
The reason is easy: The typecast has a higher binding to the value afterwards than any other operator.
Thus this should be visible:

    $var = (int)$value + (int)$other;

vs

    $var = (int) $value+(int) $other;

etc

**Comment by e-ruiz** [comment]
@dereuromark 
Your example clarified my point of view, I never needed to write anything like this, till now.

Thank you.

"Readability counts"

Maybe php would raise an syntax in this cases
```php
(int) $value;
```

=)

**Comment by dereuromark** [comment]
It wouldnt ;)
Thx for contributing.
