### ISSUE TITLE
Comments examples do not have dots at the end

### ISSUE THREAD

**Issue by JGladykowski-modus** [php-fig-rectified/fig-rectified-standards#14]
https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md

Example:
`// Recommended for better (human) readability`

Expected:
`// Recommended for better (human) readability.`

**Comment by dereuromark** [comment]
PR welcome.

**Comment by JGladykowski-modus** [comment]
```
> git push
remote: Permission to php-fig-rectified/fig-rectified-standards.git denied to JGladykowski-modus.```

**Comment by dereuromark** [comment]
You must fork and then PR with your branch.
