### ISSUE TITLE
Why are constants like TRUE, FALSE, NULL not capitalised?

### ISSUE THREAD

**Issue by halmai** [php-fig-rectified/fig-rectified-standards#17]
The constants defined by the user should be written ALL_CAPS. This is quite common in many languages, not even surprising.

For some reason, several PHP standards, including php-fig-r, say they should be written lower case. Why? 

If we want to be consistent then TRUE, FALSE and NULL also should be upper case, like the coding style of CodeIgniter also suggests. 

Can I create a pull request in order to change this? (I did not do it up till now because I didn't want to increase the noise if you don't like the idea.:))

**Comment by dereuromark** [comment]
in PHP it is common to be lowercase. See also psr2 itself.

**Comment by kAlvaro** [comment]
I believe they're normally lower-cased precisely to tell them apart from regular constants. In other languages (C comes to my mind) `TRUE` and `FALSE` are nothing but integer constants. In PHP they're a type or their own.

_Disclaimer: this is just my opinion, I haven't checked the rationale used by PHP-FIG or other groups._

**Comment by dereuromark** [comment]
We do not want to strive further from current psr standards, thus we cannot proceed here.
