### ISSUE TITLE
better inline bracing

### ISSUE THREAD

**Issue by JLuc** [php-fig-rectified/fig-rectified-standards#23]
PSR2R changes oneliner `if ($test) doit();`
into :
```
if ($test) { doit();
}
```
which is bad looking.
Is there a way to get
```
if ($test) { 
    doit();
}
```
?

**Comment by dereuromark** [comment]
should be doable by either writing an improvement or using any of the existing libraries as dependencies.

**Comment by JLuc** [comment]
I'm a bit lot. As for the improvement, in which repo / folder or kind of file should i look ?
As for an existing library, where can i browse rules so as to choose the right one ?

**Comment by dereuromark** [comment]
I would expect that the underlying core lib has some of those rules somewhere
or maybe https://github.com/slevomat/coding-standard

**Comment by JLuc** [comment]
Thank you for your pointers.
It seems `Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace` seems to be responsible for this. It was there in my ruleset seemed inactive. I somehow managed to have it work ok now.

**Comment by JLuc** [comment]
i got it : changing severity from 0 to 10 did the trick
