### ISSUE TITLE
Control Structures Keywords

### ISSUE THREAD

**Issue by ionas** [php-fig-rectified/fig-rectified-standards#4]
Control Structures keywords are actually very nice in case PHP is being used as a template language cause endif, endswitch, endforeach etc are hard to overlook.

I'd simply state:
Rule: The same file should either use ONLY braces OR keywords.
Recommendation: keywords for control structures should only be used for things like templating in php.

**Comment by dereuromark** [comment]
I added a remark about the consistency. Closing then.
